#!/bin/sh

#point /etc/rc.local to this file. should be run as root

#generate this by running iptables-save on the machine with the rules you like

#/sbin/iptables-restore < /opt/tomcat/Helios/scripts/iptables/rules.ipt

/sbin/iptables-restore <<END
# Generated by iptables-save v1.3.5 on Sat Nov 30 02:55:18 2013
*nat
:PREROUTING ACCEPT [1089:110558]
:POSTROUTING ACCEPT [95:6098]
:OUTPUT ACCEPT [95:6098]
-A PREROUTING -p tcp -m tcp --dport 8080 -j REDIRECT --to-ports 443 
COMMIT
# Completed on Sat Nov 30 02:55:18 2013
# Generated by iptables-save v1.3.5 on Sat Nov 30 02:55:18 2013
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [37:6446]
:RH-Firewall-1-INPUT - [0:0]
-A INPUT -j RH-Firewall-1-INPUT 
-A FORWARD -j RH-Firewall-1-INPUT 
-A RH-Firewall-1-INPUT -i lo -j ACCEPT 
-A RH-Firewall-1-INPUT -p icmp -m icmp --icmp-type any -j ACCEPT 
-A RH-Firewall-1-INPUT -p esp -j ACCEPT 
-A RH-Firewall-1-INPUT -p ah -j ACCEPT 
-A RH-Firewall-1-INPUT -d 224.0.0.251 -p udp -m udp --dport 5353 -j ACCEPT 
-A RH-Firewall-1-INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT 
-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT 
-A RH-Firewall-1-INPUT -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT 
-A RH-Firewall-1-INPUT -j REJECT --reject-with icmp-host-prohibited 
COMMIT
# Completed on Sat Nov 30 02:55:18 2013
END

